server:
  port: 88

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tying_video?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: tying
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
  aop:
    proxy-target-class: false
  profiles:
    active: prod


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  # mapper 映射文件路径
  type-aliases-package: com.tying.domain          # 配置哪个包下的类有默认的别名

management:
  endpoints:
    enabled-by-default: true  # 启用所有端点
    web:
      exposure:
        include: "*"          # web端暴露所有端点
  endpoint:
    health:
      show-details: always