server:
  port: 88

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tying_video?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: tying
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
  aop:
    proxy-target-class: false
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 5MB

# MyBatis 配置(和下面在 MyBatisPlus 配置一样的作用
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml  # mapper 映射文件路径
#  type-aliases-package: com.tying.domain          # 配置哪个包下的类有默认的别名

management:
  endpoints:
    enabled-by-default: true  # 启用所有端点
    web:
      exposure:
        include: "*"          # web端暴露所有端点
  endpoint:
    health:
      show-details: always

# 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml # mapper 映射文件路径
  type-aliases-package: com.tying.domain        # 配置哪个包下的类有默认的别名
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

# OSS 配置
oss:
  accessKey: 8zwVIdxxSdFagmaYdIH1IKw1WE3-7S8L9hJDpuXO
  secretKey: u_diTp6PvjqJv9zzK2fSyCIkTQ2Jt7jyW4PaRA7I
  bucket: tying-video